### ISSUE TITLE
document new v0.3.0 features and breaking changes

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1185]
~~Follow up to #1041~~

- [x] Quickstart updates
- [x] Global shared credentials (see #1041)
- [x] SSO user --> ServiceAccount mappings (see #1148 #1190)

These changes shouldn't be merged to main until v0.3.0 is released.

We are aggregating these changes in the `releas-0.3` branch.

The following will be completed post-release:

- [x] Freight aliases (see #1097 #1162 #1349)
- [x] Freight verifications and manual approvals (see #1033 #1189 #1349)
- [x] Ability to use image digests in promotion mechanisms (see #1239 #1240)
