### ISSUE TITLE
UI Catchup to backend

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1498]
# Proposed Feature

```[tasklist]
### Tasks
- [ ] https://github.com/akuity/kargo/issues/1692
- [ ] https://github.com/akuity/kargo/issues/1444
- [ ] https://github.com/akuity/kargo/issues/1536
- [ ] https://github.com/akuity/kargo/issues/1537
- [ ] https://github.com/akuity/kargo/issues/1538
- [ ] https://github.com/akuity/kargo/issues/1686
```

**Comment by krancour** [comment]
All tasks in this issue were completed. We'll continue opening issues for more narrowly-scoped UI improvements.
