### ISSUE TITLE
misc doc updates for upcoming v0.5.0

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1656]
I'm still looking for more items, but I found two things already in the docs that need to be updated and were overlooked until now:

- [x] `Freight` and `FreightReference` types have lost their `id` field since #1609, but it still appears in a few places in docs

- [x] Docs mention a `verificationResult` field, which is actually `verificationInfo`. I believe the composition of that type _might_ have changed, and we're also recording `VerificationHistory` now as well since #1645.

- [x] `Freight` has a new `alias` field, which is a convenience over the alias label. #1612

- [x] Warehouse `scanPaths` and `ignorePaths` are a major new feature being introduced in #1477. That PR doesn't contain documentation, so we will have to add it separately.

I'll update this list if/as I find more items.

**Comment by krancour** [comment]
@hiddeco if you have the bandwidth, would you be able to look at this?

**Comment by hiddeco** [comment]
Yes no problem, will tackle this tomorrow morning.

**Comment by krancour** [comment]
Will re-open if more items are found.
