### ISSUE TITLE
Prevent confusion about promoting to downstream subscribers

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1867]
# Proposed Feature

There has been confusion about promoting into a Stage, vs. promoting to downstream subscribers. Especially with a completely linear deploy pipeline.

<img width="1067" alt="image" src="https://github.com/akuity/kargo/assets/12677113/28ac3113-cc2c-431e-8531-7470d3aa4d68">

To improve this, I am proposing the following changes:

1. Remove the promote subscribers button (truck button) in UI if there is only 1 downstream subscribers. We already remove the icon if there is 0. The only time the truck matters is when you have multiple downstream subscribers. Otherwise, the UI is giving two ways to do the same thing.

2. Improve the promotion message so that it's clear that it's affecting multiple Stages. Something like

> Promoting to 3 downstream subscribers: `prod-east`, `prod-west`, `prod-central`

3. Tooltip on the button explaining what it will do:
* Promote into Stage
* Promote to downstream subscribers

# Motivation

Avoid confusion

```[tasklist]
### Tasks
- [x] Remove the promote subscribers button (truck button) in UI if there is only 1 downstream subscribers
- [x] Improve the promotion message so that it's clear that it's affecting multiple Stages
- [x] Tooltip on the buttons explaining what it will do
- [x] Promote subscribers should default to current freight
- [ ] Hide promo buttons on control flow stages
```

**Comment by krancour** [comment]
@jessesuen similar to this...

https://github.com/akuity/kargo/issues/1857

We could probably combine these two issues. Willing to edit this one to include the concerns from #1857?

**Comment by jessesuen** [comment]
Incorp@alexmt suggested one more improvement:

4. when promoting to downstream subscribers, the common case will be to promote what is currently running in the stage to the downstream. But currently, we make the user select from the freightline again. Instead, we would default to the currently running freight, but they can still select something different if desired.

> Willing to edit this one to include the concerns from https://github.com/akuity/kargo/issues/1857?

Yep. That's a good one. Added it to the tasklist

**Comment by krancour** [comment]
> the common case will be to promote what is currently running in the stage to the downstream. But currently, we make the user select from the freightline again. Instead, we would default to the currently running freight, but they can still select something different if desired.

☝️ 

It's been a frequent source of confusion. People have long thought the icons are "pull from upstream" and "push to downstream."

What if we double-down on @alexmt suggestion and also have the target icon default to what's upstream? (As long as there is only one upstream or all the upstreams have the same Freight, otherwise, no default.)

**Comment by krancour** [comment]
Deferring to v0.7.0
