### ISSUE TITLE
Revamp docs

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#645]
Docs need to be revamped
```[tasklist]
### Tasks
- [ ] https://github.com/akuity/kargo/issues/717
- [ ] https://github.com/akuity/kargo/issues/718
- [ ] https://github.com/akuity/kargo/issues/720
- [ ] https://github.com/akuity/kargo/issues/721
- [ ] https://github.com/akuity/kargo/issues/719
```

**Comment by krancour** [comment]
I've wanted this as well because the current quickstart (for example) is very `kubectl` focused and I don't expect that to be the most common way that people interact with Kargo.

I think last time we talked about this we agreed that the UI is still evolving too fast for us to keep up with UI focused documentation. So can we assume then that the revamping you propose shifts us to `kargo` CLI-centric documentation?

**Comment by morey-tech** [comment]
I'd be happy to take on this issue. Can someone outline the tasks to be done for it?

**Comment by krancour** [comment]
It seems like all the tasks associated with this issue were completed a very long time ago and we're already on to a _new_ docs refresh in #2772. Closing.
